name: Publish
run-name: "Publish Homebrew formula '${{ inputs.name }}'"

on:
    workflow_dispatch:
        inputs:
            dict:
                description: "Formula dictionary in JSON format"
                required: true
                type: string
            name:
                description: "Formula name"
                required: true
                type: string

concurrency:
    cancel-in-progress: false
    group: "${{ github.workflow }}"

env:
    FORMULA_DIR: "Formula"
    FORMULA_NAME: "${{ inputs.name }}"
    FORMULA_PATH: "Formula/${{ inputs.name }}.rb"

jobs:
    prepare:
        defaults:
            run:
                shell: bash
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Write formula
              env:
                  INPUTS_DICT: "${{ inputs.dict }}"
              run: |
                  echo "${INPUTS_DICT}" \
                  | jq -r 'to_entries.[] | "\(.key | gsub("-";"_"))=\(.value)" | @sh' \
                  | xargs sh -c 'erb "$@" "$0"' "${FORMULA_PATH}.erb" \
                  | tee "${FORMULA_PATH}"

            - uses: actions/upload-artifact@v4
              with:
                  name: formula
                  path: "${{ env.FORMULA_PATH }}"

    test:
        needs: prepare
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-13
                    - macos-15
                    - ubuntu-24.04
                    - ubuntu-24.04-arm
        defaults:
            run:
                shell: bash
        runs-on: ${{ matrix.os }}
        steps:
            - name: Install Homebrew (Optional)
              run: |
                  if ! which brew &> /dev/null; then
                    PATH="/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:${PATH}"
                  fi

                  if ! which brew &> /dev/null; then
                    NONINTERACTIVE=1 bash -c "$(
                      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
                    )"
                  fi
            - id: homebrew
              uses: Homebrew/actions/setup-homebrew@master

            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: formula
                  path: "${{ env.FORMULA_DIR }}/"

            - name: Restore cache for Homebrew
              uses: actions/cache@v4
              with:
                  key: "${{ runner.os }}-${{ runner.arch }}-homebrew-${{ steps.homebrew.outputs.gems-hash }}"
                  path: |
                      "${{ steps.homebrew.outputs.gems-path }}"
                  restore-keys: "${{ runner.os }}-${{ runner.arch }}-homebrew-"

            - name: Test formula
              run: |
                  brew style "./${FORMULA_PATH}"
                  brew reinstall --display-times --formula "./${FORMULA_PATH}"
                  brew test "${FORMULA_NAME}"
                  brew uninstall "${FORMULA_NAME}"

    update:
        needs: test
        defaults:
            run:
                shell: bash
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: formula
                  path: "${{ env.FORMULA_DIR }}/"

            - name: Update formula
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add "${FORMULA_PATH}"
                  git commit -m "Update formula '${FORMULA_NAME}'"
                  git push origin 'HEAD:${{ github.ref_name }}'
